### ISSUE TITLE
XEP-0156 _xmppconnect is vulnerable to MITM

### ISSUE THREAD

**Issue by moparisthebest** [tigase/tigase-extras#3]
Context: https://mail.jabber.org/pipermail/standards/2022-February/038759.html

Vulnerable code: https://github.com/tigase/tigase-extras/blob/cf360b62154534b36c36317b946463247422b9db/mdns/src/main/java/MDnsComponent.java#L102

**Comment by woj-tek** [comment]
Deprecated and slated for removal, [7c56d21787c737f76aa3913444b25e4ee751805e](https://github.com/tigase/tigase-extras/commit/7c56d21787c737f76aa3913444b25e4ee751805e)
